import { isCurrentRevision } from './identity.js';

const esc = value => String(value ?? '').replace(/[&<>"']/g, ch => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[ch]));
const tagChips = (tags, map) => (Array.isArray(tags) ? tags : []).map(id => map.get(id)).filter(Boolean).map(tag => `<span class="sp-anchor-tagchip" data-color="${esc(tag.color || 'slate')}">${esc(tag.name)}</span>`).join('');

export function createCoordinateRenderer({ repository, setBody, getState, setState, getTheme = () => 'day', escapeHtml = esc, formatTimestamp = value => new Date(value || 0).toLocaleString(), svg = () => '', documentRef = globalThis.document, queryRoot = null } = {}) {
    const current = () => getState?.() || { level: 'chars', charName: null, chatId: null, itemId: null, filter: null, fullTagEdit: false };
    const visible = (items, filter) => filter ? items.filter(item => item.tags?.includes(filter)) : items;
    const filterBar = (tags, active) => `<div class="sp-anchor-filterbar"><button class="sp-anchor-filter-chip${!active ? ' sp-anchor-filter-on' : ''}" data-id="">全部</button>${tags.map(tag => `<button class="sp-anchor-filter-chip sp-anchor-filter-tag${tag.id === active ? ' sp-anchor-filter-on' : ''}" data-id="${esc(tag.id)}"><span class="sp-anchor-tagchip" data-color="${esc(tag.color || 'slate')}">${esc(tag.name)}</span></button>`).join('')}</div>`;
    async function chars() {
        const all = await repository.listByChat?.() || []; const tags = await repository.getTags(); const s = current(); const groups = new Map();
        for (const bucket of all) { const items = visible(bucket.items || [], s.filter); if (!items.length) continue; const key = bucket.charName || '(未知角色)'; const group = groups.get(key) || { name: key, chatCount: 0, count: 0, latestTs: 0 }; group.chatCount++; group.count += items.length; group.latestTs = Math.max(group.latestTs, ...items.map(item => item.ts || 0)); groups.set(key, group); }
        const list = [...groups.values()].sort((a, b) => b.latestTs - a.latestTs);
        const cards = list.map(group => `<button class="sp-anchor-char-card" data-char="${esc(group.name)}"><span class="sp-anchor-chat-icon">${svg('sp-anchor-chat-svg')}</span><span class="sp-anchor-chat-main"><span class="sp-anchor-chat-name">${escapeHtml(group.name)}</span><span class="sp-anchor-chat-sub">${group.chatCount} 个聊天</span></span><span class="sp-anchor-chat-meta"><span class="sp-anchor-chat-count">${group.count}</span><span class="sp-anchor-chat-ts">${formatTimestamp(group.latestTs)}</span></span></button>`).join('');
        setBody(`<div class="sp-anchor-head sp-anchor-chars-head"><button class="sp-icon-btn sp-anchor-tagmgr-btn" title="标签管理" aria-label="标签管理">标签管理</button></div><div class="sp-anchor-scroll">${filterBar(tags, s.filter)}<div class="sp-anchor-char-list">${cards || '<div class="sp-anchor-filter-empty">没有含此标签的收藏</div>'}</div></div>`);
    }
    async function tags() {
        const list = await repository.getTags(); const state = current();
        const palette = ['rose', 'amber', 'olive', 'teal', 'indigo', 'plum', 'slate', 'clay'];
        const buckets = await repository.listByChat?.() || []; const usage = new Map();
        for (const bucket of buckets) for (const item of bucket.items || []) for (const id of item.tags || []) usage.set(id, (usage.get(id) || 0) + 1);
        const swatches = active => palette.map(color => `<button type="button" class="sp-tagmgr-swatch${color === active ? ' sp-tp-swatch-on' : ''}" data-color="${color}"><span class="sp-anchor-tagchip" data-color="${color}">A</span></button>`).join('');
        const rows = list.length ? list.map(tag => {
            const n = usage.get(tag.id) || 0;
            if (state.tagEditId === tag.id) return `<div class="sp-anchor-tagmgr-row sp-tagmgr-editing" data-id="${esc(tag.id)}"><input type="text" class="sp-tagmgr-name-input sp-input" value="${esc(tag.name)}" maxlength="20"><div class="sp-tagmgr-swatches">${swatches(state.tagEditColor)}</div><div class="sp-tagmgr-row-actions"><button type="button" class="sp-tagmgr-save sp-mini-btn"><i class="fa-solid fa-check"></i></button><button type="button" class="sp-tagmgr-cancel sp-mini-btn"><i class="fa-solid fa-xmark"></i></button></div></div>`;
            if (state.tagDeleteId === tag.id) return `<div class="sp-anchor-tagmgr-row sp-tagmgr-confirming" data-id="${esc(tag.id)}"><span class="sp-tagmgr-confirm-text">删除「${esc(tag.name)}」？将从 ${n} 条收藏移除</span><div class="sp-tagmgr-row-actions"><button type="button" class="sp-tagmgr-del-yes sp-mini-btn sp-mini-btn-danger">删除</button><button type="button" class="sp-tagmgr-del-no sp-mini-btn">取消</button></div></div>`;
            return `<div class="sp-anchor-tagmgr-row" data-id="${esc(tag.id)}"><span class="sp-anchor-tagchip" data-color="${esc(tag.color || 'slate')}">${esc(tag.name)}</span><span class="sp-tagmgr-usage">${n} 条</span><div class="sp-tagmgr-row-actions"><button type="button" class="sp-tagmgr-edit sp-icon-btn" title="改名 / 改色"><i class="fa-solid fa-pen"></i></button><button type="button" class="sp-tagmgr-del sp-icon-btn" title="删除标签"><i class="fa-solid fa-trash"></i></button></div></div>`;
        }).join('') : '<div class="sp-anchor-filter-empty">还没有标签，在下方新建第一个</div>';
        setBody(`<div class="sp-anchor-head sp-anchor-tagmgr-head"><button class="sp-anchor-back" data-to="chars"><i class="fa-solid fa-chevron-left"></i></button><span class="sp-anchor-head-title">标签管理</span><span class="sp-anchor-head-count">${list.length} 个</span></div><div class="sp-anchor-scroll"><div class="sp-anchor-tagmgr-new"><input type="text" class="sp-tagmgr-new-name sp-input" placeholder="新建标签名…" maxlength="20"><div class="sp-tagmgr-swatches sp-tagmgr-new-swatches">${swatches(state.tagNewColor || 'rose')}</div><button type="button" class="sp-tagmgr-new-add sp-mini-btn"><i class="fa-solid fa-plus"></i> 新建</button></div><div class="sp-anchor-tagmgr-list">${rows}</div></div>`);
    }
    async function chats(charName) {
        const all = (await repository.listByChat?.() || []).filter(bucket => !charName || (bucket.charName || '(未知角色)') === charName); const tags = await repository.getTags(); const s = current(); const buckets = all.map(bucket => { const items = visible(bucket.items || [], s.filter); return { ...bucket, items, count: items.length, latestTs: Math.max(0, ...items.map(item => item.ts || 0)) }; }).filter(bucket => bucket.items.length);
        const cards = buckets.map(bucket => `<button class="sp-anchor-chat-card" data-chatid="${esc(bucket.chatId ?? '')}"><span class="sp-anchor-chat-icon">${svg('sp-anchor-chat-svg')}</span><span class="sp-anchor-chat-main"><span class="sp-anchor-chat-name">${escapeHtml(bucket.chatName || '(未命名聊天)')}</span><span class="sp-anchor-chat-sub">${escapeHtml(bucket.charName || '')}</span></span><span class="sp-anchor-chat-meta"><span class="sp-anchor-chat-count">${bucket.count}</span><span class="sp-anchor-chat-ts">${formatTimestamp(bucket.latestTs)}</span></span></button>`).join('');
        setBody(`<div class="sp-anchor-head"><button class="sp-anchor-back" data-to="chars">‹</button><span class="sp-anchor-head-title">${escapeHtml(charName || '(未知角色)')}</span><span class="sp-anchor-head-count">${buckets.length} 个聊天</span></div><div class="sp-anchor-scroll">${filterBar(tags, s.filter)}<div class="sp-anchor-chat-list">${cards || '<div class="sp-anchor-filter-empty">没有含此标签的收藏</div>'}</div></div>`);
    }
    async function items(chatId) {
        const bucket = (await repository.listByChat?.() || []).find(entry => String(entry.chatId) === String(chatId)); if (!bucket) return chars(); const tags = await repository.getTags(); const map = new Map(tags.map(tag => [tag.id, tag])); const s = current(); const list = visible(bucket.items, s.filter);
        setBody(`<div class="sp-anchor-head"><button class="sp-anchor-back" data-to="chats" data-char="${esc(bucket.charName)}">‹</button><span class="sp-anchor-head-title">${escapeHtml(bucket.chatName || bucket.charName || '收藏')}</span><span class="sp-anchor-head-count">${list.length} 条</span></div><div class="sp-anchor-scroll">${filterBar(tags, s.filter)}<div class="sp-anchor-item-list">${list.map(item => `<button class="sp-anchor-item-card" data-id="${esc(item.id)}"><span class="sp-anchor-item-tags">${tagChips(item.tags, map)}</span><span class="sp-anchor-item-main"><span class="sp-anchor-item-floor">#${item.floorIndex ?? '?'}</span><span class="sp-anchor-item-preview">${escapeHtml(item.textPreview || '(无正文预览)')}</span><span class="sp-anchor-item-ts">${formatTimestamp(item.ts)}</span></span></button>`).join('') || '<div class="sp-anchor-filter-empty">没有含此标签的收藏</div>'}</div></div>`);
    }
    async function full(itemId, revision = null, theme = null) {
        theme = theme || getTheme?.() || 'day';
        const item = await repository.getItem(itemId); if (!item || (revision && !isCurrentRevision(revision, getState?.()))) return chars(); const tags = await repository.getTags(); const map = new Map(tags.map(tag => [tag.id, tag]));
        setState?.({ level: 'full', itemId }); const edit = current().fullTagEdit ? `<div class="sp-anchor-full-tagedit"><div class="sp-anchor-ftag-chips">${tags.map(tag => `<button class="sp-anchor-ftag-chip${item.tags?.includes(tag.id) ? ' sp-tp-chip-on' : ''}" data-id="${esc(tag.id)}"><span class="sp-anchor-tagchip" data-color="${esc(tag.color || 'slate')}">${esc(tag.name)}</span></button>`).join('')}</div><div class="sp-anchor-ftag-new"><input class="sp-anchor-ftag-name sp-input" placeholder="新建标签名…"></div><div class="sp-anchor-ftag-foot"><button class="sp-anchor-ftag-add sp-mini-btn">新增</button><button class="sp-anchor-ftag-done sp-mini-btn">完成</button></div></div>` : `<div class="sp-anchor-full-tags">${tagChips(item.tags, map)}<button class="sp-anchor-tag-edit sp-mini-btn">编辑标签</button></div>`; setBody(`<div class="sp-anchor-head"><button class="sp-anchor-back" data-to="items" data-chatid="${esc(item.chatId)}">‹</button><span class="sp-anchor-head-title">${escapeHtml(item.charName || '')}<span class="sp-anchor-head-floor"> · #${item.floorIndex ?? '?'}</span></span><span class="sp-anchor-head-actions"><button class="sp-icon-btn sp-anchor-fullscreen" title="全屏浏览">⛶</button><button class="sp-icon-btn sp-anchor-del" title="删除此收藏">×</button></span></div><div class="sp-anchor-scroll">${edit}<div class="sp-anchor-full-host" id="sp-anchor-full-host"></div><div class="sp-anchor-full-ts">收藏于 ${formatTimestamp(item.ts)}</div></div><div class="sp-anchor-fs-resize" title="拖拽调整大小"></div>`);
        const host = queryRoot?.querySelector?.('#sp-anchor-full-host') || documentRef?.querySelector?.('#sp-anchor-full-host');
        if (host) { const shadow = host.shadowRoot || host.attachShadow?.({ mode: 'open' }); if (shadow) { const night = theme === 'night'; const fg = night ? '#D8D9DA' : '#2c2e2a'; const bg = night ? '#272829' : '#F6F4E8'; const link = night ? '#A8A49E' : '#DC9B9B'; shadow.innerHTML = `<style>:host{all:initial;display:block}.sp-anchor-snap{display:block;color:${fg};background:${bg};padding:16px 18px !important;margin:0 !important;border:none !important;border-radius:10px;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"PingFang SC","Microsoft YaHei",sans-serif;font-size:12px;line-height:1.6;word-break:break-word}.sp-anchor-snap img{max-width:100%;height:auto}.sp-anchor-snap a{color:${link}}.sp-anchor-snap q:before,.sp-anchor-snap q:after{content:''}</style><div class="mes_text sp-anchor-snap">${item.html || ''}</div>`; } }
        return item;
    }
    async function render() { const s = current(); if (s.level === 'full' && s.itemId) return full(s.itemId); if (s.level === 'items' && s.chatId != null) return items(s.chatId); if (s.level === 'chats') return chats(s.charName); if (s.level === 'tags') return tags(); return chars(); }
    return { render, chars, chats, items, full, tags, filterBar };
}

export function createFullscreenController({ body, sheet, documentRef = globalThis.document } = {}) {
    let escHandler = null; let gesture = null;
    const clearInline = () => { if (!body?.style) return; for (const key of ['left','top','right','bottom','width','height']) body.style[key] = ''; };
    const clear = () => { body?.classList?.remove('sp-anchor-fs-on'); sheet?.classList?.remove('sp-fs-flat'); documentRef?.body?.classList?.remove('sp-anchor-fs-lock'); clearInline(); if (escHandler) documentRef?.removeEventListener?.('keydown', escHandler); escHandler = null; };
    const toggle = () => { if (!body) return false; const on = body.classList.toggle('sp-anchor-fs-on'); sheet?.classList?.toggle('sp-fs-flat', on); documentRef?.body?.classList?.toggle('sp-anchor-fs-lock', on); if (!on) clearInline(); if (on && !escHandler) { escHandler = event => { if (event.key === 'Escape') clear(); }; documentRef?.addEventListener?.('keydown', escHandler); } return on; };
    const beginGesture = (mode, event) => { if (!body?.classList?.contains('sp-anchor-fs-on') || (globalThis.innerWidth || 0) <= 640) return; gesture = { mode, x: event.clientX, y: event.clientY, left: body.offsetLeft, top: body.offsetTop, width: body.offsetWidth, height: body.offsetHeight }; };
    const moveGesture = event => { if (!gesture || !body) return; if (event.buttons === 0) return endGesture(); const dx = event.clientX - gesture.x; const dy = event.clientY - gesture.y; if (gesture.mode === 'move') { body.style.left = `${gesture.left + dx}px`; body.style.top = `${gesture.top + dy}px`; } else { body.style.width = `${Math.max(280, gesture.width + dx)}px`; body.style.height = `${Math.max(240, gesture.height + dy)}px`; } };
    const endGesture = () => { gesture = null; };
    return { toggle, clear, beginGesture, moveGesture, endGesture, destroy() { endGesture(); clear(); } };
}
